2023-03-24 09:28:21,159 INFO    StreamThr :8033 [internal.py:wandb_internal():87] W&B internal server running at pid: 8033, started at: 2023-03-24 09:28:21.159126
2023-03-24 09:28:21,160 DEBUG   HandlerThread:8033 [handler.py:handle_request():144] handle_request: status
2023-03-24 09:28:21,161 INFO    WriterThread:8033 [datastore.py:open_for_write():85] open: /home/bluesk/Documents/discrete-graph-diffusion/outputs/2023-03-24/09-23-34/wandb/run-20230324_092821-gskzmuuk/run-gskzmuuk.wandb
2023-03-24 09:28:21,161 DEBUG   SenderThread:8033 [sender.py:send():336] send: header
2023-03-24 09:28:21,163 DEBUG   SenderThread:8033 [sender.py:send():336] send: run
2023-03-24 09:28:21,918 ERROR   SenderThread:8033 [internal_api.py:execute():246] 401 response executing GraphQL.
2023-03-24 09:28:21,918 ERROR   SenderThread:8033 [internal_api.py:execute():247] {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2023-03-24 09:28:21,918 ERROR   SenderThread:8033 [sender.py:send_run():931] The API key is either invalid or missing, or the host is incorrect. To resolve this issue, you may try running the 'wandb login --host [hostname]' command. The host defaults to 'https://api.wandb.ai' if not specified. (Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 929, in send_run
    self._init_run(run, config_value_dict)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 968, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise err
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1664, in upsert_run
    response = self.gql(
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 215, in gql
    ret = self._retry_gql(
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/util.py", line 1092, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/bluesk/.local/lib/python3.10/site-packages/wandb/util.py", line 1025, in no_retry_auth
    raise CommError(
wandb.errors.CommError: The API key is either invalid or missing, or the host is incorrect. To resolve this issue, you may try running the 'wandb login --host [hostname]' command. The host defaults to 'https://api.wandb.ai' if not specified. (Error 401: Unauthorized)
2023-03-24 09:28:22,169 DEBUG   HandlerThread:8033 [handler.py:handle_request():144] handle_request: shutdown
2023-03-24 09:28:22,169 INFO    HandlerThread:8033 [handler.py:finish():842] shutting down handler
2023-03-24 09:28:22,919 INFO    SenderThread:8033 [sender.py:finish():1504] shutting down sender
2023-03-24 09:28:23,163 INFO    WriterThread:8033 [datastore.py:close():298] close: /home/bluesk/Documents/discrete-graph-diffusion/outputs/2023-03-24/09-23-34/wandb/run-20230324_092821-gskzmuuk/run-gskzmuuk.wandb
